Repository SRGSSR/srganalytics-apple, pull requests merged in 2023-09, with the labels that each got.

#77 Update RSI cases for unit tests
  Tests/SRGAnalyticsTests/MediaTestCase.m
Labels: internal

#76 Update to Commanders Act version 5
  Demo/Demo.xcconfig
  Demo/SRGAnalytics-demo.xcodeproj/project.pbxproj
  Demo/SRGAnalytics-demo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Demo/Sources/Application/AppDelegate.m
  Demo/Sources/Demos/DemosViewController.m
  Demo/Sources/Simple/SimpleViewController.m
  Demo/Sources/SwiftUI/SwiftUIView.swift
  Demo/Sources/WebTester/WebTesterViewController~ios.m
  Package.resolved
  Package.swift
  Sources/SRGAnalytics/NSBundle+SRGAnalytics.h
  Sources/SRGAnalytics/NSBundle+SRGAnalytics.m
  Sources/SRGAnalytics/SRGAnalyticsConfiguration.m
  Sources/SRGAnalytics/SRGAnalyticsEventLabels.m
  Sources/SRGAnalytics/SRGAnalyticsLabels+Private.h
  Sources/SRGAnalytics/SRGAnalyticsNotifications.m
  Sources/SRGAnalytics/SRGAnalyticsTracker+Private.h
  Sources/SRGAnalytics/SRGAnalyticsTracker.m
  Sources/SRGAnalytics/UIViewController+SRGAnalytics.m
  Sources/SRGAnalytics/include/SRGAnalytics.h
  Sources/SRGAnalytics/include/SRGAnalyticsConfiguration.h
  Sources/SRGAnalytics/include/SRGAnalyticsEventLabels.h
  Sources/SRGAnalytics/include/SRGAnalyticsLabels.h
  Sources/SRGAnalytics/include/SRGAnalyticsNotifications.h
  Sources/SRGAnalytics/include/SRGAnalyticsTracker.h
  Sources/SRGAnalytics/include/UIViewController+SRGAnalytics.h
  Sources/SRGAnalyticsMediaPlayer/SRGComScoreMediaPlayerTracker.m
  Sources/SRGAnalyticsMediaPlayer/SRGMediaPlayerTracker.m
  Sources/SRGAnalyticsSwiftUI/SRGAnalyticsPageViewTracking.swift
  Tests/SRGAnalyticsIdentity-tests.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/SRGAnalyticsIdentityTests/IdentityTestCase.m
  Tests/SRGAnalyticsTests/ComScoreDataProviderTestCase.m
  Tests/SRGAnalyticsTests/ComScoreMediaPlayerTestCase.m
  Tests/SRGAnalyticsTests/ComScoreTrackerTestCase.m
  Tests/SRGAnalyticsTests/ConfigurationTestCase.m
  Tests/SRGAnalyticsTests/DataProviderTestCase.m
  Tests/SRGAnalyticsTests/EventLabelsTestCase.m
  Tests/SRGAnalyticsTests/MediaPlayerTestCase.m
  Tests/SRGAnalyticsTests/NSNotificationCenter+Tests.h
  Tests/SRGAnalyticsTests/NSNotificationCenter+Tests.m
  Tests/SRGAnalyticsTests/TrackerSingletonSetup.h
  Tests/SRGAnalyticsTests/TrackerSingletonSetup.m
  Tests/SRGAnalyticsTests/TrackerTestCase.m
  Tests/SRGAnalyticsTests/XCTestCase+Tests.h
  Tests/SRGAnalyticsTests/XCTestCase+Tests.m
  docs/GETTING_STARTED.md
  docs/README.md
Labels: enhancement

#78 Local tests don't need real parameters
  Tests/SRGAnalyticsTests/ConfigurationTestCase.m
Labels: enhancement, internal
